### ISSUE TITLE
Discord Module "Connection Failure" On Linux

### ISSUE THREAD

**Issue by Calhym** [bitfocus/companion-module-discord-api#33] opened 2024-06-27 00:21 UTC
I'm trying to switch to using Linux, and companion seems to be a good way to control the Stream Deck.
I was able to use "shell path local" to somewhat work around using terminal commands under my main account, and I assume a similar issue might be in place for the discord app. However I'm knew to this and not sure if this is the case.

(NOTE: the shell work around was to use "echo <password> | su - <username> -c "<commands>". Not secure but was for testing.)

**To Reproduce**

1.Open discord on your machine
2. Add connection to "Connections" tab in Companion
3. Create discord application and follow the installing steps
4. Open the "Logs" option for the module
5. Turn the module on and off.
6. last error "debug: Login err: {}"
![module-log](https://github.com/bitfocus/companion-module-discord-api/assets/105756253/b8b441a6-f682-4615-b514-43c34a955b60)

**Expected behaviour**
Considering I'm still learning this all, my "expected behavior" is to be able to control discord.

- Companion Version
I tried Stable Versions v3.2.1 to v3.3.1
Along with Beta Version 3.4.0+706-main-849878c4

**Additional context**
This is being done on a repetitively clean install of Linux. Specifically PopOS.
I have tried both the Discord version in the PopOS repository and the DEB file from the Official Discord website. (I believe both of these are the "official" version.)

**Comment by thedist** [comment] 2024-06-27 10:19
If Companion is running on the same machine as Discord, Discord is from the official Discord website, and you're not doing any sort of sandboxing of apps, then there's not much support I can offer.

I don't use Discord on my Linux machines so can't test myself, but others who have ran in to issues previously on linux have all been due to sandboxing, so I'd recommend you investigate that on your end.

**Comment by Calhym** [comment] 2024-06-27 12:42
I didn't consider sandboxing might be happening. I will try to look into that over the next few days.

If I find anything I'll be sure to post here. Or if I find the "fix".

**Comment by JarzaCode** [comment] 2024-10-21 02:18
I am having the same issue, but discord is sandboxed. Let me know if there's a fix!

**Comment by thedist** [comment] 2024-10-21 10:14
The fix is to not sandbox Discord, or configure your sandbox to allow the IPC between Companion and Discord.

There's nothing that can be done on this modules side if a sandbox is being used to explicitly block the connection that's required.

**Comment by JarzaCode** [comment] 2024-10-21 12:52
How would I do this with a flatpak? I have flatseal, so I can easily allow requests. Is there a certain interface that I have to allow discord to receive?

**Comment by thedist** [comment] 2024-10-21 14:40
I don't use Flatpak so I can't offer much guidance other than to suggest reading through their documentation and seeing how to allow IPC communication, as that's how the Companion module communicates with the Discord client running on the system.

**Comment by JarzaCode** [comment] 2024-10-24 16:24
I'm just wondering if there's a certain interface the module communicates on that needs to be allowed by flatpak. Like, for example, localhost:8080

**Comment by JarzaCode** [comment] 2024-10-24 16:26
Most likely the Inter-process Communications checkmark on Flatseal, right?

**Comment by thedist** [comment] 2024-12-27 23:11
Closing this issue as there have been no further reports, and the issue appears to entirely be related to installing Discord in a sandbox which by design would block connections such as this module unless configured otherwise.

**Closed by thedist** 2024-12-27 23:11 UTC
Labels: bug
